### ISSUE TITLE
Documento DRS

### ISSUE THREAD

**Issue by YaelStO** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-jdgras#1]
[DOCUMENTO DRS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-jdgras/files/13453840/DOCUMENTO.DRS.pdf)]

**Comment by josealfredo79** [comment]
Por completar bien el documento no se puede evaluar...

**Comment by josealfredo79** [comment]
No se puede liberar no hay calificacion

**Comment by yanet02** [comment]
CALIFICACIÓN = **28/30**

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
